# Generated by Django 2.1.1 on 2018-12-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('url_id', models.CharField(max_length=254, unique=True)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('cited_times', models.IntegerField(null=True)),
                ('source', models.CharField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'citation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('date', models.IntegerField(null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=1000, null=True)),
                ('cited_times', models.IntegerField(null=True)),
                ('abstract', models.CharField(max_length=7000, null=True)),
                ('keywords', models.CharField(max_length=7000, null=True)),
                ('authors', models.ManyToManyField(to='crawler.Author')),
                ('cited', models.ManyToManyField(to='crawler.Citation')),
            ],
            options={
                'db_table': 'paper',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
    ]
