# Generated by Django 2.1.1 on 2018-12-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20181225_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='title',
        ),
    ]
