# Generated by Django 2.1.1 on 2018-12-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20181226_2037'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rankcache',
            table='rankCache',
        ),
    ]
